### PR TITLE
Make repository attractive for contributors

### PR DESCRIPTION
**Pull request by ezhlobo**
It updates all eslint dependencies and updates flow-bin (via npm).

Addresses all linting issues and adds `npm run lint` command to CI, so Travis will help to keep code style of the project consistent.

### CODE REVIEW

**Comment by ForbesLindesay** [comment]
Thanks for doing all this. I like that you've added generated files to the .gitignore (they also need deleting if we're going to do that). Can we actually remove eslint and add prettier instead?  You can see an example of this configured at:

 - https://github.com/ForbesLindesay/tsgen/blob/master/.prettierrc
 - https://github.com/ForbesLindesay/tsgen/blob/master/package.json

husky & lint-staged ensure that prettier is run on every commit.

**Comment by ezhlobo** [comment]
@ForbesLindesay let's discuss it a bit first.

1. I have not added generated files to .gitignore, but I added them to .eslintignore. So we can use linter. 

   We still can get rid of generated files in repository, but it requires some additional work (because we need to modify npm scripts and test it). So let's create an issue for this and do it separately?

2. Why do you think that removing of eslint is a good idea? We can't validate the code on CI with just prettier, can we? If you would like to add automate-formatting let's combine them together by following that documentation: https://prettier.io/docs/en/eslint.html. With husky and lint-staged ;).

Thank you for your configuration files BTW, they are helpful as I've not worked with prettier before!

**Comment by ForbesLindesay** [comment]
`prettier --check` validates the code is formatted according to prettier's standards. We already have flow for code style. I agree, I had misread the code regarding .gitignore - can be a separate pr.

**Comment by ezhlobo** [comment]
@ForbesLindesay what do you think about 'code-quality rules' provided by eslint: https://prettier.io/docs/en/comparison.html

Should we throw them out?

**Comment by ForbesLindesay** [comment]
I don't mind adding some of those (I'm a big fan of prefer-const in particular) but we get such a huge amount from flow, that the little added by eslint isn't that important, and the overhead of maintaining eslintignore files etc. may not be worth it.

I'd say I don't have a very strong opinion on this, but we definitely shouldn't have eslint rules enabled for things like whitespace or single vs. double quotes - that's prettier's job.

**Comment by ezhlobo** [comment]
@ForbesLindesay I think I got your point. Thank you for spending time on explanation.

My plan is to get rid of eslint completely and setup prettier. I'll leave [current config for prettier](https://github.com/pugjs/babel-plugin-transform-react-pug/blob/master/.prettierrc) (it's the same as you sent above from `tsgen` project).

Next step is to cover all files by flow, otherwise we can lose some important things.

Will wait for your approvement for this plan in order to avoid misunderstanding.

**Comment by ForbesLindesay** [comment]
Yes, that sounds like a good plan.

**Comment by wolfgang42** [comment]
@ezhlobo When I try to commit after pulling master (and running npm install) I get:
```
$ git commit
husky > npm run -s precommit (node v8.9.4)

'lint-staged' is not recognized as an internal or external command,
operable program or batch file.

husky > pre-commit hook failed (add --no-verify to bypass)
```

I also notice that when I run `npm install` I get a lot of changes to package-lock.json. Is there a missing dependency or something?

**Comment by ezhlobo** [comment]
@wolfgang42 yes, I've realized this as well and created a new PR since this one had been merged: #39.

**Pull request merged**
